
# 🌍 Lab 4: การประมวลผลข้อมูลด้วย NumPy และ GeoPandas
## วิชา GE 234 Basic Programming for Geographers

### 🎯 **วัตถุประสงค์**
1. เข้าใจการใช้ **NumPy** สำหรับการประมวลผลข้อมูลทางภูมิศาสตร์ เช่น ข้อมูล Raster และพิกัด
2. ใช้ **GeoPandas** ในการจัดการและวิเคราะห์ข้อมูลเวกเตอร์ เช่น **Shapefile**
3. สามารถดำเนินการทางสถิติกับข้อมูลพิกัดและชั้นข้อมูลทางภูมิศาสตร์ได้
4. สามารถใช้ NumPy และ GeoPandas ร่วมกันเพื่อวิเคราะห์ข้อมูลได้

---

## 🔹 ตัวอย่างที่ 1: ใช้ NumPy คำนวณข้อมูล NDVI จากภาพ Raster

In [1]:

import numpy as np

# สร้างข้อมูลตัวอย่างสำหรับภาพ NDVI (Normalized Difference Vegetation Index)
nir = np.array([[0.7, 0.8, 0.6], [0.9, 0.5, 0.3], [0.4, 0.7, 0.2]])
red = np.array([[0.3, 0.4, 0.2], [0.5, 0.3, 0.1], [0.2, 0.3, 0.1]])

# คำนวณค่า NDVI
ndvi = (nir - red) / (nir + red)

print("ค่า NDVI:")
print(ndvi)

ค่า NDVI:
[[0.4        0.33333333 0.5       ]
 [0.28571429 0.25       0.5       ]
 [0.33333333 0.4        0.33333333]]


## 🔹 ตัวอย่างที่ 2: ใช้ NumPy คำนวณค่าเฉลี่ยและค่ามากสุดของ NDVI

In [2]:

print(f"ค่าเฉลี่ย NDVI: {np.mean(ndvi):.2f}")
print(f"ค่า NDVI สูงสุด: {np.max(ndvi):.2f}")
print(f"ค่า NDVI ต่ำสุด: {np.min(ndvi):.2f}")

ค่าเฉลี่ย NDVI: 0.37
ค่า NDVI สูงสุด: 0.50
ค่า NDVI ต่ำสุด: 0.25


## 🔹 ตัวอย่างที่ 3: ใช้ GeoPandas โหลดและวิเคราะห์ข้อมูล Shapefile

In [6]:

import geopandas as gpd

# โหลดข้อมูลชั้นข้อมูลจังหวัดของประเทศไทย
gdf = gpd.read_file("https://data.opendevelopmentmekong.net/th/dataset/8f3fa1b8-cb5c-48c8-9fd7-d3c213ea23db/resource/1559cee4-fedc-4330-be9c-d8cf3dd75015/download/tha_admbnda_adm1_rtsd_20190221.zip")

# แสดงข้อมูล 5 แถว
print(gdf.head())

   Shape_Leng  Shape_Area        ADM1_EN        ADM1_TH ADM1_PCODE ADM1_REF  \
0    3.927244    0.275313  Amnat Charoen     อำนาจเจริญ       TH37     None
1    1.739908    0.079210      Ang Thong        อ่างทอง       TH15     None
2    2.417227    0.131339        Bangkok  กรุงเทพมหานคร       TH10     None
3    4.414998    0.340784      Bueng Kan         บึงกาฬ       TH38     None
4    8.701860    0.844537       Buri Ram      บุรีรัมย์       TH31     None

  ADM1ALT1EN ADM1ALT2EN ADM1ALT1TH ADM1ALT2TH   ADM0_EN    ADM0_TH ADM0_PCODE  \
0       None       None       None       None  Thailand  ประเทศไทย         TH
1       None       None       None       None  Thailand  ประเทศไทย         TH
2       None       None       None       None  Thailand  ประเทศไทย         TH
3       None       None       None       None  Thailand  ประเทศไทย         TH
4       None       None       None       None  Thailand  ประเทศไทย         TH

        date    validOn validTo  \
0 2019-02-18 2019-02-21     NaT
1 2019-02-18 2019-02-21     NaT
2 2019-02-18 2019-02-21     NaT
3 2019-02-18 2019-02-21     NaT
4 2019-02-18 2019-02-21     NaT

                                            geometry
0  POLYGON ((104.95982 16.28359, 104.95986 16.283...
1  POLYGON ((100.33319 14.79853, 100.33341 14.798...
2  POLYGON ((100.61389 13.95462, 100.61428 13.954...
3  POLYGON ((103.40497 18.44898, 103.40619 18.448...
4  POLYGON ((102.93029 15.79514, 102.93029 15.795...


## 🔹 ตัวอย่างที่ 4: คำนวณพื้นที่ของแต่ละจังหวัด

In [13]:
# ตรวจสอบค่า CRS (Coordinate Reference System)
print(gdf.crs)

# Reproject to a projected CRS for accurate area calculation (e.g., UTM Zone 47N for parts of Thailand)
gdf_projected = gdf.to_crs(epsg=32647)

# คำนวณพื้นที่ของแต่ละจังหวัด (หน่วยเป็นตารางเมตร) จากข้อมูลที่ถูกฉายภาพ
gdf["area_sqkm"] = gdf_projected.geometry.area / 1e6

# แสดงพื้นที่จังหวัด 5 อันดับแรกที่ใหญ่ที่สุด
print(gdf.nlargest(5, "area_sqkm")[["ADM1_EN", "area_sqkm"]])

EPSG:4326
              ADM1_EN     area_sqkm
9          Chiang Mai  22159.519971
28  Nakhon Ratchasima  20750.869676
15       Kanchanaburi  19436.356316
68                Tak  17266.546740
71   Ubon Ratchathani  15636.863442


## 🔹 ตัวอย่างที่ 5: ใช้ GeoPandas ทำ Spatial Join

In [15]:

# โหลดข้อมูลชั้นข้อมูลอำเภอ
gdf_districts = gpd.read_file("https://data.opendevelopmentmekong.net/th/dataset/8f3fa1b8-cb5c-48c8-9fd7-d3c213ea23db/resource/1559cee4-fedc-4330-be9c-d8cf3dd75015/download/tha_admbnda_adm1_rtsd_20190221.zip")

# ทำ Spatial Join ระหว่างอำเภอกับจังหวัด
gdf_joined = gpd.sjoin(gdf_districts, gdf, how="inner", predicate="within")

# แสดงตัวอย่างข้อมูลที่เชื่อมโยงกัน
print(gdf_joined.head())

   Shape_Leng_left  Shape_Area_left   ADM1_EN_left   ADM1_TH_left  \
0         3.927244         0.275313  Amnat Charoen     อำนาจเจริญ
1         1.739908         0.079210      Ang Thong        อ่างทอง
2         2.417227         0.131339        Bangkok  กรุงเทพมหานคร
3         4.414998         0.340784      Bueng Kan         บึงกาฬ
4         8.701860         0.844537       Buri Ram      บุรีรัมย์

  ADM1_PCODE_left ADM1_REF_left ADM1ALT1EN_left ADM1ALT2EN_left  \
0            TH37          None            None            None
1            TH15          None            None            None
2            TH10          None            None            None
3            TH38          None            None            None
4            TH31          None            None            None

  ADM1ALT1TH_left ADM1ALT2TH_left  ... ADM1ALT2EN_right ADM1ALT1TH_right  \
0            None            None  ...             None             None
1            None            None  ...             None             None
2            None            None  ...             None             None
3            None            None  ...             None             None
4            None            None  ...             None             None

  ADM1ALT2TH_right ADM0_EN_right ADM0_TH_right ADM0_PCODE_right date_right  \
0             None      Thailand     ประเทศไทย               TH 2019-02-18
1             None      Thailand     ประเทศไทย               TH 2019-02-18
2             None      Thailand     ประเทศไทย               TH 2019-02-18
3             None      Thailand     ประเทศไทย               TH 2019-02-18
4             None      Thailand     ประเทศไทย               TH 2019-02-18

   validOn_right  validTo_right     area_sqkm
0     2019-02-21            NaT   3290.635392
1     2019-02-21            NaT    943.956101
2     2019-02-21            NaT   1571.323599
3     2019-02-21            NaT   4012.682238
4     2019-02-21            NaT  10095.554993

[5 rows x 35 columns]


# 📝 **กิจกรรมในแลป**

1. **แบบฝึกหัด 1**: ใช้ NumPy คำนวณค่า **Mean, Max, Min** ของค่า NDVI ในอาร์เรย์ที่สร้างขึ้นเอง
2. **แบบฝึกหัด 2**: ใช้ GeoPandas โหลด **Shapefile** ของจังหวัด และคำนวณพื้นที่ของแต่ละจังหวัด
3. **แบบฝึกหัด 3**: ใช้ GeoPandas ทำ **Spatial Join** ระหว่างข้อมูลจังหวัดและอำเภอ
4. **แบบฝึกหัด 4**: ใช้ NumPy และ GeoPandas ร่วมกันเพื่อหาข้อมูลจังหวัดที่มี NDVI เฉลี่ยสูงสุด

แบบฝึกหัด 1: ใช้ NumPy คำนวณค่า Mean, Max, Min ของค่า NDVI **ในอาร์เรย์ที่สร้างขึ้นเอง** **bold text**

In [19]:
# แบบฝึกหัด 1
print(f"ค่าเฉลี่ย NDVI: {np.mean(ndvi):.2f}")
print(f"ค่า NDVI สูงสุด: {np.max(ndvi):.2f}")
print(f"ค่า NDVI ต่ำสุด: {np.min(ndvi):.2f}")

ค่าเฉลี่ย NDVI: 0.37
ค่า NDVI สูงสุด: 0.50
ค่า NDVI ต่ำสุด: 0.25

**แบบฝึกหัด 2**: ใช้ GeoPandas โหลด Shapefile ของจังหวัด และคำนวณพื้นที่ของแต่ละจังหวัด

In [22]:
import geopandas as gpd

# โหลดข้อมูลชั้นข้อมูลจังหวัดของประเทศไทย
gdf_exercise2 = gpd.read_file("https://data.opendevelopmentmekong.net/th/dataset/8f3fa1b8-cb5c-48c8-9fd7-d3c213ea23db/resource/1559cee4-fedc-4330-be9c-d8cf3dd75015/download/tha_admbnda_adm1_rtsd_20190221.zip")

# Reproject to a projected CRS for accurate area calculation (e.g., UTM Zone 47N for parts of Thailand)
gdf_exercise2_projected = gdf_exercise2.to_crs(epsg=32647)

# คำนวณพื้นที่ของแต่ละจังหวัด (หน่วยเป็นตารางเมตร) จากข้อมูลที่ถูกฉายภาพ
gdf_exercise2["area_sqkm"] = gdf_exercise2_projected.geometry.area / 1e6

# แสดงข้อมูล 5 แถวแรกพร้อมพื้นที่
print(gdf_exercise2[["ADM1_EN", "area_sqkm"]].head())

         ADM1_EN     area_sqkm
0  Amnat Charoen   3290.635392
1      Ang Thong    943.956101
2        Bangkok   1571.323599
3      Bueng Kan   4012.682238
4       Buri Ram  10095.554993

In [ ]:
แบบฝึกหัด 3: ใช้ GeoPandas ทำ Spatial Join ระหว่างข้อมูลจังหวัดและอำเภอของประเทศกัมพูชา

In [44]:
import geopandas as gpd
from IPython.display import display

gdf = gpd.read_file("https://data.opendevelopmentcambodia.net/dataset/b0609661-5c22-41ee-a569-848648620136/resource/861ce9cf-2349-404c-beb4-7421326f0007/download/district-whre-wash-implemented.zip")

print("ข้อมูลดิบ (gdf.head()):")
display(gdf.head())

gdf_districts = gpd.read_file("https://data.opendevelopmentcambodia.net/dataset/b0609661-5c22-41ee-a569-848648620136/resource/861ce9cf-2349-404c-beb4-7421326f0007/download/district-whre-wash-implemented.zip")

gdf_joined = gpd.sjoin(gdf_districts, gdf, how="inner", predicate="within")

print("ข้อมูลที่ผ่าน Spatial Join (gdf_joined ทั้งหมด):")
display(gdf_joined)

ข้อมูลดิบ (gdf.head()):

,map_id,ngo,district,appriviati,province,fOOD,cASH,WASH,health,shelter,edu,protect,year,programme,language,geometry
0,39,World Vision International,Mongkol Borei,WVI,Banteay Meanchey,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, WAS...",English,"POLYGON ((293143.691 1500648.998, 293188.035 1..."
1,42,World Vision International,Phnum Srok,WVI,Banteay Meanchey,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, water supply, WAS...",English,"POLYGON ((324686.004 1542760.873, 324822.316 1..."
2,43,World Vision International,Preah Netr Preah,WVI,Banteay Meanchey,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, CLT...",English,"POLYGON ((301239.973 1520363.998, 310773.535 1..."
3,50,World Vision International,Thma Puok,WVI,Banteay Meanchey,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, BFCI, PD Health, Water supply, CVA/...",English,"POLYGON ((288074.098 1575975.123, 292733.973 1..."
4,48,World Vision International,Svay Chek,WVI,Banteay Meanchey,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, CLT...",English,"POLYGON ((275462.191 1540938.623, 275819.91 15..."

ข้อมูลที่ผ่าน Spatial Join (gdf_joined ทั้งหมด):

,map_id_left,ngo_left,district_left,appriviati_left,province_left,fOOD_left,cASH_left,WASH_left,health_left,shelter_left,...,fOOD_right,cASH_right,WASH_right,health_right,shelter_right,edu_right,protect_right,year_right,programme_right,language_right
0,39,World Vision International,Mongkol Borei,WVI,Banteay Meanchey,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, WAS...",English
1,42,World Vision International,Phnum Srok,WVI,Banteay Meanchey,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, water supply, WAS...",English
2,43,World Vision International,Preah Netr Preah,WVI,Banteay Meanchey,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, CLT...",English
3,50,World Vision International,Thma Puok,WVI,Banteay Meanchey,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, BFCI, PD Health, Water supply, CVA/...",English
4,48,World Vision International,Svay Chek,WVI,Banteay Meanchey,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, CLT...",English
5,5,Caritas Cambodia,Banan,Caritas,Battambang,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
6,40,World Vision International,Moung Ruessei,WVI,Battambang,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CLTS, CVA/ISAF, C...",English
7,41,World Vision International,Phnum Proek,WVI,Battambang,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,No,2018,"Education, Health/Nutrition, CLTS, CVA/ISAF, C...",English
8,37,World Vision International,Koas Krala,WVI,Battambang,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,No,2018,"Education, Health/Nutrition, CLTS, CVA/ISAF, O...",English
9,14,Caritas Cambodia;World Vision International,Rukh Kiri,Caritas;WVI,Battambang,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
10,31,World Vision International,Baribour,WVI,Kampong Chhnang,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, CLT...",English
11,21,HEKS;World Vision International,Chol Kiri,HEKS;WVI,Kampong Chhnang,Yes,No,Yes,No,No,...,Yes,No,Yes,No,No,No,No,2018,Developing Rural Communities,English
12,22,HEKS;World Vision International,Rolea B'ier,HEKS,Kampong Chhnang,Yes,No,Yes,No,No,...,Yes,No,Yes,No,No,No,No,2018,Developing Rural Communities,English
13,20,HEKS,Tuek Phos,HEKS,Kampong Chhnang,Yes,No,Yes,No,No,...,Yes,No,Yes,No,No,No,No,2018,Developing Rural Communities,English
14,47,World Vision International,Samraong Tong,WVI,Kampong Speu,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Educaiton, Health/Nutrition, Water Supply, CLT...",English
15,23,Oxfam,Baray,Oxfam,Kampong Thom,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
16,11,Caritas Cambodia;Oxfam;World Vision International,Kampong Svay,Caritas;Oxfam;WVI,Kampong Thom,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
17,10,Caritas Cambodia; Oxfam,Stueng Saen,Caritas,Kampong Thom,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
18,30,Oxfam;World Vision International,Prasat Ballangk,Oxfam;WVI,Kampong Thom,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
19,27,Oxfam,Prasat Sambour,Oxfam,Kampong Thom,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
20,28,Oxfam,Sandan,Oxfam,Kampong Thom,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
21,16,Caritas Cambodia;World Vision International,Santuk,Caritas;WVI,Kampong Thom,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,No,Yes,2018,"Health/Nutrition, CLTS, Water Supply, WASH in ...",English
22,4,Action Against Hunger;World Vision International,Stoung,AAH;Oxfam;WVI,Kampong Thom,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,No,No,2018,Nutrition Sensitive Hygiene and Health at Comm...,English
23,2,Action Against Hunger,Dang Tong,AAH,Kampot,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,No,No,2018,Nutrition Sensitive Hygiene and Health at Comm...,English
24,3,Action Against Hunger,Kampong Trach,AAH,Kampot,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,No,No,2018,Nutrition Sensitive Hygiene and Health at Comm...,English
25,35,World Vision International,Khsach Kandal,WVI,Kandal,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CP and CESP.",English
26,45,World Vision International,S'ang,WVI,Kandal,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CLTS, CVA/ISAF, K...",English
27,7,Caritas Cambodia,Pech Chreada,Caritas,Mondul Kiri,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
28,33,World Vision International,Chey Saen,WVI,Preah Vihear,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CLTS, Water Suppl...",English
29,34,World Vision International,Chhaeb,WVI,Preah Vihear,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Heatlh/Nutrition, CLTS, Water Suppl...",English
30,1,Action Against Hunger,Choam Ksant,AAH,Preah Vihear,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,No,No,2018,"Nutrional Resilience, integrated program combi...",English
31,6,Caritas Cambodia,Kuleaen,Caritas,Preah Vihear,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
32,44,World Vision International,Rovieng,WVI,Preah Vihear,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, WASH and CP.",English
33,15,Caritas Cambodia;World Vision International,Sangkum Thmei,Caritas;WVI,Preah Vihear,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
34,49,World Vision International,Tbaeng Mean Chey,WVI,Preah Vihear,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CLTS, Water Suppl...",English
35,17,HEKS,Ba Phnum,HEKS,Prey Veng,Yes,No,Yes,No,No,...,Yes,No,Yes,No,No,No,No,2018,Developing Rural Communities,English
36,24,Oxfam,Kandieng,Oxfam,Pursat,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
37,26,Oxfam,Krakor,Oxfam,Pursat,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
38,19,HEKS,Phnum Kravanh,HEKS,Pursat,Yes,No,Yes,No,No,...,Yes,No,Yes,No,No,No,No,2018,Developing Rural Communities,English
39,12,Caritas Cambodia;World Vision International,Chi Kraeng,Caritas;WVI,Siemreap,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
40,38,World Vision International,Kralanh,WVI,Siemreap,No,No,Yes,No,No,...,No,No,Yes,No,No,Yes,Yes,2018,"Education, CF, SA4CP, Youth for Change, WASH, ...",English
41,13,Caritas Cambodia;World Vision International,Puok,Caritas;WVI,Siemreap,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
42,8,Caritas Cambodia,Soutr Nikom,Caritas,Siemreap,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
43,9,Caritas Cambodia,Svay Leu,Caritas,Siemreap,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,Yes,Yes,No,No,2018,"Community Development program, Cliamte Change ...",English
44,51,World Vision International,Varin,WVI,Siemreap,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Water Supply, WASH in School, Healt...",English
45,32,World Vision International,Borei Cholsar,WVI,Takeo,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CLTS, WASH in Sch...",English
46,36,World Vision International,Kiri Vong,WVI,Takeo,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, CLTS, Water Suppl...",English
47,25,Oxfam,Kaoh Andaet,Oxfam,Takeo,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
48,46,World Vision International,Samraong,WVI,Takeo,No,No,Yes,Yes,No,...,No,No,Yes,Yes,No,Yes,Yes,2018,"Education, Health/Nutrition, Water Supply, CLT...",English
49,29,Oxfam,Treang,Oxfam,Takeo,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,No,No,No,2018,"WASH facility at HH and community level, Food ...",English
50,18,HEKS,Memot,HEKS,Tboung Khmum,Yes,No,Yes,No,No,...,Yes,No,Yes,No,No,No,No,2018,Sustainable agriculture and Value Chain,English

แบบฝึกหัด 4: ใช้ NumPy และ GeoPandas ร่วมกันเพื่อหาข้อมูลจังหวัดที่มี NDVI เฉลี่ยสูงสุด

In [45]:
# ตรวจสอบว่า gdf_exercise2 และ ndvi ถูกสร้างขึ้นแล้ว
if 'gdf_exercise2' not in locals():
    print("gdf_exercise2 ไม่ถูกสร้างขึ้น กรุณารันแบบฝึกหัด 2 ก่อน")
    # หากยังไม่มี ให้โหลดข้อมูลใหม่
    import geopandas as gpd
    gdf_exercise2 = gpd.read_file("https://data.opendevelopmentmekong.net/th/dataset/8f3fa1b8-cb5c-48c8-9fd7-d3c213ea23db/resource/1559cee4-fedc-4330-be9c-d8cf3dd75015/download/tha_admbnda_adm1_rtsd_20190221.zip")
    gdf_exercise2_projected = gdf_exercise2.to_crs(epsg=32647)
    gdf_exercise2["area_sqkm"] = gdf_exercise2_projected.geometry.area / 1e6

if 'ndvi' not in locals():
    print("ndvi ไม่ถูกสร้างขึ้น กรุณารันตัวอย่างที่ 1 ก่อน")
    import numpy as np
    nir = np.array([[0.7, 0.8, 0.6], [0.9, 0.5, 0.3], [0.4, 0.7, 0.2]])
    red = np.array([[0.3, 0.4, 0.2], [0.5, 0.3, 0.1], [0.2, 0.3, 0.1]])
    ndvi = (nir - red) / (nir + red)

# 1. คำนวณค่าเฉลี่ยของ NDVI จาก NumPy array
mean_ndvi_value = np.mean(ndvi)
print(f"ค่าเฉลี่ย NDVI จาก NumPy array: {mean_ndvi_value:.2f}")

# 2. จำลองการกำหนดค่า NDVI เฉลี่ยให้กับแต่ละจังหวัดใน GeoDataFrame
# ในสถานการณ์จริง คุณจะต้องมีข้อมูล NDVI raster และทำการวิเคราะห์แบบ zonal statistics
# แต่ในที่นี้ เราจะใช้ค่าเฉลี่ยจาก NumPy array ที่มีเป็นตัวอย่าง
# และกระจายค่าไปตามจังหวัดต่างๆ เพื่อให้เห็นการทำงานร่วมกัน
# เพื่อให้เห็นความแตกต่าง ผมจะสุ่มค่าเล็กน้อยรอบๆ mean_ndvi_value
np.random.seed(42) # เพื่อให้ผลลัพธ์สอดคล้องกันทุกครั้งที่รัน
gdf_exercise2['simulated_avg_ndvi'] = mean_ndvi_value + (np.random.rand(len(gdf_exercise2)) - 0.5) * 0.1 # สุ่มค่า +/- 0.05 จากค่าเฉลี่ย

print("\nGeoDataFrame พร้อมค่า NDVI จำลอง (5 แถวแรก):")
display(gdf_exercise2[['ADM1_EN', 'simulated_avg_ndvi']].head())

# 3. หาจังหวัดที่มีค่า NDVI เฉลี่ยสูงสุด
province_with_max_ndvi = gdf_exercise2.loc[gdf_exercise2['simulated_avg_ndvi'].idxmax()]

print("\nจังหวัดที่มีค่า NDVI เฉลี่ยสูงสุด:")
print(f"ชื่อจังหวัด: {province_with_max_ndvi['ADM1_EN']}")
print(f"ค่า NDVI เฉลี่ย: {province_with_max_ndvi['simulated_avg_ndvi']:.2f}")

ค่าเฉลี่ย NDVI จาก NumPy array: 0.37

GeoDataFrame พร้อมค่า NDVI จำลอง (5 แถวแรก):

         ADM1_EN  simulated_avg_ndvi
0  Amnat Charoen            0.358089
1      Ang Thong            0.415706
2        Bangkok            0.393834
3      Bueng Kan            0.380501
4       Buri Ram            0.336237

จังหวัดที่มีค่า NDVI เฉลี่ยสูงสุด:
ชื่อจังหวัด: Trang
ค่า NDVI เฉลี่ย: 0.42